import { useMemo, useState } from 'react';
import { Link, NavLink, Route, Routes } from 'react-router-dom';
import { BarChart3, Boxes, ChevronRight, LayoutDashboard, Menu, Package, Search, ShoppingBag, Sparkles, Store, Tag, Users, X } from 'lucide-react';
import { currency, initialOrders, initialProducts, type Product } from './lib/catalog';

const nav = [
  { label: 'Home', to: '/' },
  { label: 'Collection', to: '/collection' },
  { label: 'Our Story', to: '/story' },
];

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="site-shell">
    <header className="store-header"><div className="container header-inner">
      <button className="icon-btn mobile-only" onClick={() => setOpen((v) => !v)} aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button>
      <Link className="wordmark" to="/">Ashu <span>Silks</span></Link>
      <nav className={open ? 'store-nav mobile-open' : 'store-nav'}>{nav.map((item) => <NavLink key={item.to} onClick={() => setOpen(false)} to={item.to}>{item.label}</NavLink>)}</nav>
      <Link className="header-admin" to="/admin"><LayoutDashboard size={17} /> Manage</Link>
    </div></header>
    {children}
    <footer className="store-footer"><div className="container footer-grid"><div><div className="wordmark dark">Ashu <span>Silks</span></div><p>Curated sarees, considered details and a quieter way to shop occasionwear.</p></div><div><div className="footer-title">Explore</div><Link to="/collection">Collection</Link><Link to="/story">Our Story</Link><Link to="/admin">Owner Dashboard</Link></div><div><div className="footer-title">Store</div><span>Sarjapur Main Road</span><span>Bengaluru 560035</span><span>Open daily · 10 AM–10 PM</span></div></div></footer>
  </div>;
}

function ProductCard({ product }: { product: Product }) {
  return <article className="product-card"><div className="product-media"><video src={product.image} muted autoPlay loop playsInline /><span className="product-chip">{product.category}</span></div><div className="product-body"><div className="product-meta"><span>{product.fabric}</span><span>{product.color}</span></div><h3>{product.name}</h3><div className="price-row"><strong>{currency(product.price)}</strong>{product.compareAt && <del>{currency(product.compareAt)}</del>}</div><button className="text-action">View piece <ChevronRight size={16} /></button></div></article>;
}

function Home() {
  const featured = initialProducts.filter((p) => p.featured);
  return <><section className="hero-section"><div className="hero-media"><video src="/ashuvedio.mp4" autoPlay muted loop playsInline /></div><div className="hero-shade" /><div className="container hero-copy"><span className="eyebrow-light">A modern saree house in Bengaluru</span><h1>Silks that feel <em>like you.</em></h1><p>Tradition, edited with restraint. Discover Kanjeevarams, Banarasis and everyday handlooms chosen for modern wardrobes.</p><div className="hero-actions"><Link className="button button-light" to="/collection">Explore collection <ChevronRight size={17} /></Link><Link className="hero-link" to="/story">The Ashu Silks story</Link></div></div></section><section className="intro-section"><div className="container split"><div><span className="eyebrow">The edit</span><h2>Fine details, not loud decoration.</h2></div><div><p className="lead-copy">A premium storefront should feel composed before it feels clever. This collection is built around fabric, fall, colour and the small details that make a saree worth keeping.</p><Link className="inline-link" to="/collection">Shop the edit <ChevronRight size={16} /></Link></div></div></section><section className="collection-section"><div className="container"><div className="section-heading-row"><div><span className="eyebrow">Featured</span><h2>Pieces worth stopping for</h2></div><Link className="inline-link" to="/collection">View all <ChevronRight size={16} /></Link></div><div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section><section className="experience-section"><div className="container experience-grid"><div className="experience-card dark-panel"><Sparkles size={22} /><span className="eyebrow-light">Private styling</span><h2>For weddings, firsts and everything that deserves a little more thought.</h2><p>Tell us the occasion, your colours and your comfort zone. We will build a short edit instead of handing you the whole rack.</p><Link className="button button-light" to="/story">Discover our approach</Link></div><div className="experience-card image-panel"><div className="image-overlay"><span className="eyebrow-light">Ashu Silks</span><h3>The confidence of knowing you chose well.</h3></div></div></div></section></>;
}

function Collection() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const filtered = useMemo(() => initialProducts.filter((p) => (category === 'All' || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <main><section className="page-hero"><div className="container"><span className="eyebrow-light">Collection</span><h1>Curated for the way you actually dress.</h1><p>Explore the edit by fabric, mood and occasion.</p></div></section><section className="collection-section"><div className="container"><div className="toolbar"><div className="searchbox"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the collection" /></div><div className="filters">{['All','Kanjeevaram','Banarasi','Designer','Cotton'].map((item) => <button key={item} className={category === item ? 'filter active' : 'filter'} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="product-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section></main>;
}

function Story() { return <main><section className="story-hero"><div className="container narrow"><span className="eyebrow">Our story</span><h1>A saree store can feel premium without feeling distant.</h1><p>We built Ashu Silks around an old retail idea: listen first, show less, and make every recommendation feel personal.</p></div></section><section className="story-copy"><div className="container story-grid"><div><span className="eyebrow">What matters</span><h2>Fabric first. Details second. Pressure never.</h2></div><div className="prose"><p>Our edit favours pieces with an honest relationship between weave, colour and occasion. We would rather help you leave with one exceptional saree than five forgettable ones.</p><p>That philosophy also shapes this website. No clutter, no fake urgency, no checkout theatre hiding the important stuff. Just a store that makes the collection easy to understand.</p></div></div></section></main>; }

function AdminLayout({ children }: { children: React.ReactNode }) {
  const items = [[LayoutDashboard, 'Overview', '/admin'], [Package, 'Products', '/admin/products'], [ShoppingBag, 'Orders', '/admin/orders'], [Tag, 'Collections', '/admin/collections'], [Users, 'Customers', '/admin/customers'], [BarChart3, 'Analytics', '/admin/analytics'], [Store, 'Storefront', '/admin/storefront']] as const;
  return <div className="admin-layout"><aside className="admin-sidebar"><Link className="admin-brand" to="/admin"><span className="admin-mark">AS</span><span><strong>Ashu Silks</strong><small>Owner workspace</small></span></Link><nav>{items.map(([Icon, label, to]) => <NavLink end={to === '/admin'} key={to} to={to}><Icon size={18} />{label}</NavLink>)}</nav><Link className="back-store" to="/">← View storefront</Link></aside><section className="admin-main"><div className="admin-topbar"><div><span className="admin-kicker">Owner workspace</span><h1>Control the store without touching code.</h1></div><div className="admin-user"><span className="status-dot" /> Live storefront <span className="owner-avatar">AS</span></div></div>{children}</section></div>;
}

function AdminOverview() { const revenue = initialOrders.reduce((sum, order) => sum + order.total, 0); const lowStock = initialProducts.filter((p) => p.stock <= 5).length; return <div className="admin-content"><div className="metric-grid"><Metric icon={BarChart3} label="Revenue tracked" value={currency(revenue)} detail="from recent orders" /><Metric icon={Package} label="Active products" value={String(initialProducts.filter((p) => p.status === 'active').length)} detail="catalog is healthy" /><Metric icon={ShoppingBag} label="Open orders" value={String(initialOrders.filter((o) => !['delivered','cancelled'].includes(o.status)).length)} detail="need attention" /><Metric icon={Boxes} label="Low stock" value={String(lowStock)} detail="restock recommended" /></div><div className="admin-panels"><section className="panel"><div className="panel-head"><div><span className="admin-kicker">Recent activity</span><h2>Orders</h2></div><Link to="/admin/orders">View all</Link></div>{initialOrders.map((order) => <div className="order-row" key={order.id}><div><strong>{order.id}</strong><span>{order.customer} · {order.createdAt}</span></div><div className="order-right"><strong>{currency(order.total)}</strong><span className={`badge ${order.status}`}>{order.status}</span></div></div>)}</section><section className="panel"><div className="panel-head"><div><span className="admin-kicker">Merchandising</span><h2>Inventory pulse</h2></div><Link to="/admin/products">Manage</Link></div><div className="inventory-bars">{initialProducts.map((product) => <div key={product.id} className="bar-row"><div><span>{product.name}</span><strong>{product.stock}</strong></div><div className="bar-track"><div style={{ width: `${Math.min(product.stock * 3, 100)}%` }} /></div></div>)}</div></section></div></div>; }

function Metric({ icon: Icon, label, value, detail }: { icon: typeof BarChart3; label: string; value: string; detail: string }) { return <div className="metric-card"><div className="metric-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }

function ProductAdmin() { const [products, setProducts] = useState(initialProducts); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Product | null>(null); const visible = products.filter((p) => p.name.toLowerCase().includes(search.toLowerCase())); const update = (id: string, patch: Partial<Product>) => setProducts((list) => list.map((p) => p.id === id ? { ...p, ...patch } : p)); return <div className="admin-content"><div className="admin-section-head"><div><span className="admin-kicker">Catalog control</span><h2>Products</h2><p>Edit price, stock, visibility, categories and merchandising without code.</p></div><button className="button button-dark" onClick={() => setSelected({ id: `AS-${String(products.length + 1).padStart(3,'0')}`, name: 'New Saree', category: 'Designer', price: 0, stock: 0, status: 'draft', featured: false, fabric: 'Silk', color: 'Ivory', description: '', image: '/ashuvedio.mp4', createdAt: new Date().toISOString().slice(0,10) })}>+ Add product</button></div><div className="admin-toolbar"><div className="searchbox"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search products" /></div><span className="count-label">{visible.length} products</span></div><div className="data-table"><div className="table-head"><span>Product</span><span>Category</span><span>Price</span><span>Stock</span><span>Status</span><span>Action</span></div>{visible.map((product) => <div className="table-row" key={product.id}><div className="product-table"><div className="thumb"><video src={product.image} muted autoPlay loop playsInline /></div><div><strong>{product.name}</strong><span>{product.id}</span></div></div><span>{product.category}</span><strong>{currency(product.price)}</strong><span className={product.stock <= 5 ? 'danger' : ''}>{product.stock}</span><span className={`badge ${product.status}`}>{product.status}</span><button className="table-action" onClick={() => setSelected(product)}>Edit</button></div>)}</div>{selected && <ProductModal product={selected} onClose={() => setSelected(null)} onSave={(updated) => { if (products.some((p) => p.id === updated.id)) update(updated.id, updated); else setProducts((list) => [updated, ...list]); setSelected(null); }} />}</div>; }

function ProductModal({ product, onClose, onSave }: { product: Product; onClose: () => void; onSave: (p: Product) => void }) { const [draft, setDraft] = useState(product); const set = <K extends keyof Product>(key: K, value: Product[K]) => setDraft((d) => ({ ...d, [key]: value })); return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="admin-kicker">Product editor</span><h2>{draft.id}</h2></div><button className="icon-btn" onClick={onClose}><X size={20} /></button></div><div className="form-grid"><label>Name<input value={draft.name} onChange={(e) => set('name', e.target.value)} /></label><label>Category<select value={draft.category} onChange={(e) => set('category', e.target.value as Product['category'])}><option>Kanjeevaram</option><option>Banarasi</option><option>Designer</option><option>Cotton</option></select></label><label>Price<input type="number" value={draft.price} onChange={(e) => set('price', Number(e.target.value))} /></label><label>Compare-at<input type="number" value={draft.compareAt ?? ''} onChange={(e) => set('compareAt', e.target.value ? Number(e.target.value) : undefined)} /></label><label>Stock<input type="number" value={draft.stock} onChange={(e) => set('stock', Number(e.target.value))} /></label><label>Status<select value={draft.status} onChange={(e) => set('status', e.target.value as Product['status'])}><option>active</option><option>draft</option><option>archived</option></select></label><label>Fabric<input value={draft.fabric} onChange={(e) => set('fabric', e.target.value)} /></label><label>Colour<input value={draft.color} onChange={(e) => set('color', e.target.value)} /></label><label className="full">Description<textarea value={draft.description} rows={4} onChange={(e) => set('description', e.target.value)} /></label><label className="toggle full"><input type="checkbox" checked={draft.featured} onChange={(e) => set('featured', e.target.checked)} /><span>Feature this product on the homepage</span></label></div><div className="modal-actions"><button className="button button-muted" onClick={onClose}>Cancel</button><button className="button button-dark" onClick={() => onSave(draft)}>Save changes</button></div></div></div>; }

function SimpleAdmin({ title, description, icon: Icon }: { title: string; description: string; icon: typeof BarChart3 }) { return <div className="admin-content"><div className="empty-admin"><div className="metric-icon large"><Icon size={22} /></div><span className="admin-kicker">Module ready</span><h2>{title}</h2><p>{description}</p><span className="coming-soon">Designed as an owner-controlled module</span></div></div>; }

function Admin() { return <AdminLayout><Routes><Route index element={<AdminOverview />} /><Route path="products" element={<ProductAdmin />} /><Route path="orders" element={<SimpleAdmin icon={ShoppingBag} title="Orders" description="Track order state, customer details and fulfilment from one workflow." />} /><Route path="collections" element={<SimpleAdmin icon={Tag} title="Collections" description="Create curated seasonal edits, control navigation and feature merchandising groups." />} /><Route path="customers" element={<SimpleAdmin icon={Users} title="Customers" description="Manage customer profiles, enquiry history and repeat-customer context." />} /><Route path="analytics" element={<SimpleAdmin icon={BarChart3} title="Analytics" description="Review sales, catalogue performance and conversion signals without clutter." />} /><Route path="storefront" element={<SimpleAdmin icon={Store} title="Storefront" description="Control homepage sections, navigation labels and customer-facing content." />} /></Routes></AdminLayout>; }

export default function App() { return <Routes><Route path="/*" element={<StorefrontRoutes />} /><Route path="/admin/*" element={<Admin />} /></Routes>; }

function StorefrontRoutes() { return <Shell><Routes><Route path="/" element={<Home />} /><Route path="/collection" element={<Collection />} /><Route path="/story" element={<Story />} /></Routes></Shell>; }
